# tasks file for keepasshttp
---
- name: mono-runtime
  apt:
    name: mono-runtime
    update_cache: no

- name: plugin
  get_url:
    url: https://github.com/pfn/keepasshttp/raw/master/KeePassHttp.plgx
    dest: /usr/lib/keepass2/Plugins/
    mode: 0644
...
